[package]
name = "deliverytracker"
version = "0.1.0"
authors = ["B4TT3RY <gb4tt3ry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tide"]

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.9.0", features = ["attributes"] }
async-trait = "0.1.48"
scraper = "0.12.0"
surf = "2.2.0"
tide = { version = "0.16.0", optional = true }
serde = "1.0.125"
serde_json = "1.0.64"
regex = "1.4.5"
juniper = "0.15.4"
lazy_static = "1.4.0"
